spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G6sWhsMNcDrwdR7mKck
      secret-key: ODyHrcm0AuMLobxHWl4IWM2vsqnh65
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello-3

      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: 213409bfb6f64fcd9478fda69f2251b1

  #阿里云对象上传
#  alicloud:
#    access-key: LTAI4G6sWhsMNcDrwdR7mKck
#    secret-key: ODyHrcm0AuMLobxHWl4IWM2vsqnh65
#    oss:
#      endpoint: oss-cn-beijing.aliyuncs.com
#      bucket: gulimall-hello-3

  application:
    name: gulimall-third-party

server:
  port: 30000